### ISSUE TITLE
Compile Failure with Ubuntu 24.04

### ISSUE THREAD

**Issue by Ardy123** [MeowIce/nvidia-legacy#25]
First off, thank you for putting this together. 

Second, I noticed a compile error when it attempts to compile the kernel module for ubuntu 24.04 (6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC)

This is with the 340.108-patched-6.8 release.

the compiler error is...
```
   /tmp/selfgz5614/kernel/nv-linux.h:2262:52: error: passing argument 6 of 'get_user_pages_remote' from incompatible pointer type [-Werror=incompatible-pointer-types]
    2262 |                                             pages, vmas, NULL);
         |                                                    ^~~~
         |                                                    |
         |                                                    struct vm_area_struct **
   In file included from /tmp/selfgz5614/kernel/nv-linux.h:68:
   ./include/linux/mm.h:2445:33: note: expected 'int *' but argument is of type 'struct vm_area_struct **'
    2445 |                            int *locked);
         |                            ~~~~~^~~~~~
   /tmp/selfgz5614/kernel/nv-linux.h:2261:23: error: too many arguments to function 'get_user_pages_remote'
    2261 |                return get_user_pages_remote(mm, start, nr_pages, flags,
         |                       ^~~~~~~~~~~~~~~~~~~~~
   ./include/linux/mm.h:2442:6: note: declared here
    2442 | long get_user_pages_remote(struct mm_struct *mm,
         |      ^~~~~~~~~~~~~~~~~~~~~
```

Thanks

**Comment by nautiluschan** [comment]
+1

**Comment by lproven** [comment]
also +1

**Comment by kda2210** [comment]
I noticed a compile error when it attempts to compile the kernel module for ubuntu 24.04

**Comment by kda2210** [comment]
Hello,

I'm happy to let you know that I was able to get the 340.108 driver working on kernel 6.11.

I've created a patch and started publishing information on GitHub. You're welcome to use it — here’s the link:
👉 https://github.com/kda2210/nvidia-340-ubuntu-24.04/

I'm writing to you from Russia. If my work is helpful to you, I would really appreciate it if you could help me in return by spreading the word about my project on English-speaking forums or websites. Unfortunately, my English is not good enough to do this effectively myself.

Thank you very much in advance!
